package Modelo;
// Generated 24/01/2017 15:55:32 by Hibernate Tools 4.3.1



/**
 * TbCombustivel generated by hbm2java
 */
public class Combustivel  implements java.io.Serializable {


     private int idCombustivel;
     private String txtCombustivel;

    public Combustivel() {
    }

	
    public Combustivel(int idCombustivel) {
        this.idCombustivel = idCombustivel;
    }
    public Combustivel(int idCombustivel, String txtCombustivel) {
       this.idCombustivel = idCombustivel;
       this.txtCombustivel = txtCombustivel;
    }
   
    public int getIdCombustivel() {
        return this.idCombustivel;
    }
    
    public void setIdCombustivel(int idCombustivel) {
        this.idCombustivel = idCombustivel;
    }
    public String getTxtCombustivel() {
        return this.txtCombustivel;
    }
    
    public void setTxtCombustivel(String txtCombustivel) {
        this.txtCombustivel = txtCombustivel;
    }




}


