package Modelo;
// Generated 24/01/2017 15:55:32 by Hibernate Tools 4.3.1



/**
 * TbFuncao generated by hbm2java
 */
public class Funcao  implements java.io.Serializable {


     private int idFuncao;
     private String txtFuncao;

    public Funcao() {
    }

	
    public Funcao(int idFuncao) {
        this.idFuncao = idFuncao;
    }
    public Funcao(int idFuncao, String txtFuncao) {
       this.idFuncao = idFuncao;
       this.txtFuncao = txtFuncao;
    }
   
    public int getIdFuncao() {
        return this.idFuncao;
    }
    
    public void setIdFuncao(int idFuncao) {
        this.idFuncao = idFuncao;
    }
    public String getTxtFuncao() {
        return this.txtFuncao;
    }
    
    public void setTxtFuncao(String txtFuncao) {
        this.txtFuncao = txtFuncao;
    }




}


