package Model;
// Generated 24/01/2017 15:55:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbRevisao generated by hbm2java
 */
public class Revisao  implements java.io.Serializable {


     private int idRevisao;
     private int idVeiculo;
     private String itensAVerificar;
     private String itensVerificados;
     private String trocasEfetuadas;
     private String problemasRemanescentes;
     private Integer idUsuario;
     private Date dataRealizacao;
     private Double odometro;
     private String observacao;
     private Character concluida;

    public Revisao() {
    }

	
    public Revisao(int idRevisao, int idVeiculo) {
        this.idRevisao = idRevisao;
        this.idVeiculo = idVeiculo;
    }
    public Revisao(int idRevisao, int idVeiculo, String itensAVerificar, String itensVerificados, String trocasEfetuadas, String problemasRemanescentes, Integer idUsuario, Date dataRealizacao, Double odometro, String observacao, Character concluida) {
       this.idRevisao = idRevisao;
       this.idVeiculo = idVeiculo;
       this.itensAVerificar = itensAVerificar;
       this.itensVerificados = itensVerificados;
       this.trocasEfetuadas = trocasEfetuadas;
       this.problemasRemanescentes = problemasRemanescentes;
       this.idUsuario = idUsuario;
       this.dataRealizacao = dataRealizacao;
       this.odometro = odometro;
       this.observacao = observacao;
       this.concluida = concluida;
    }
   
    public int getIdRevisao() {
        return this.idRevisao;
    }
    
    public void setIdRevisao(int idRevisao) {
        this.idRevisao = idRevisao;
    }
    public int getIdVeiculo() {
        return this.idVeiculo;
    }
    
    public void setIdVeiculo(int idVeiculo) {
        this.idVeiculo = idVeiculo;
    }
    public String getItensAVerificar() {
        return this.itensAVerificar;
    }
    
    public void setItensAVerificar(String itensAVerificar) {
        this.itensAVerificar = itensAVerificar;
    }
    public String getItensVerificados() {
        return this.itensVerificados;
    }
    
    public void setItensVerificados(String itensVerificados) {
        this.itensVerificados = itensVerificados;
    }
    public String getTrocasEfetuadas() {
        return this.trocasEfetuadas;
    }
    
    public void setTrocasEfetuadas(String trocasEfetuadas) {
        this.trocasEfetuadas = trocasEfetuadas;
    }
    public String getProblemasRemanescentes() {
        return this.problemasRemanescentes;
    }
    
    public void setProblemasRemanescentes(String problemasRemanescentes) {
        this.problemasRemanescentes = problemasRemanescentes;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getDataRealizacao() {
        return this.dataRealizacao;
    }
    
    public void setDataRealizacao(Date dataRealizacao) {
        this.dataRealizacao = dataRealizacao;
    }
    public Double getOdometro() {
        return this.odometro;
    }
    
    public void setOdometro(Double odometro) {
        this.odometro = odometro;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Character getConcluida() {
        return this.concluida;
    }
    
    public void setConcluida(Character concluida) {
        this.concluida = concluida;
    }




}


