package Model;
// Generated 24/01/2017 15:55:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbSaida generated by hbm2java
 */
public class Saida  implements java.io.Serializable {


     private int idSaida;
     private Date dataSaida;
     private int idVeiculo;
     private int idUsuario;
     private double odometroSaida;
     private String motorista;
     private String destino;
     private Date dataRetorno;
     private Double odometroRetorno;
     private Character autorizacao;

    public Saida() {
    }

	
    public Saida(int idSaida, Date dataSaida, int idVeiculo, int idUsuario, double odometroSaida, String motorista, String destino) {
        this.idSaida = idSaida;
        this.dataSaida = dataSaida;
        this.idVeiculo = idVeiculo;
        this.idUsuario = idUsuario;
        this.odometroSaida = odometroSaida;
        this.motorista = motorista;
        this.destino = destino;
    }
    public Saida(int idSaida, Date dataSaida, int idVeiculo, int idUsuario, double odometroSaida, String motorista, String destino, Date dataRetorno, Double odometroRetorno, Character autorizacao) {
       this.idSaida = idSaida;
       this.dataSaida = dataSaida;
       this.idVeiculo = idVeiculo;
       this.idUsuario = idUsuario;
       this.odometroSaida = odometroSaida;
       this.motorista = motorista;
       this.destino = destino;
       this.dataRetorno = dataRetorno;
       this.odometroRetorno = odometroRetorno;
       this.autorizacao = autorizacao;
    }
   
    public int getIdSaida() {
        return this.idSaida;
    }
    
    public void setIdSaida(int idSaida) {
        this.idSaida = idSaida;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public int getIdVeiculo() {
        return this.idVeiculo;
    }
    
    public void setIdVeiculo(int idVeiculo) {
        this.idVeiculo = idVeiculo;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public double getOdometroSaida() {
        return this.odometroSaida;
    }
    
    public void setOdometroSaida(double odometroSaida) {
        this.odometroSaida = odometroSaida;
    }
    public String getMotorista() {
        return this.motorista;
    }
    
    public void setMotorista(String motorista) {
        this.motorista = motorista;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public Date getDataRetorno() {
        return this.dataRetorno;
    }
    
    public void setDataRetorno(Date dataRetorno) {
        this.dataRetorno = dataRetorno;
    }
    public Double getOdometroRetorno() {
        return this.odometroRetorno;
    }
    
    public void setOdometroRetorno(Double odometroRetorno) {
        this.odometroRetorno = odometroRetorno;
    }
    public Character getAutorizacao() {
        return this.autorizacao;
    }
    
    public void setAutorizacao(Character autorizacao) {
        this.autorizacao = autorizacao;
    }




}


