package Model;
// Generated 24/01/2017 15:55:32 by Hibernate Tools 4.3.1



/**
 * TbTipoVeiculo generated by hbm2java
 */
public class TipoVeiculo  implements java.io.Serializable {


     private int idTipoVeiculo;
     private String finalidade;
     private String txtTipo;

    public TipoVeiculo() {
    }

	
    public TipoVeiculo(int idTipoVeiculo) {
        this.idTipoVeiculo = idTipoVeiculo;
    }
    public TipoVeiculo(int idTipoVeiculo, String finalidade, String txtTipo) {
       this.idTipoVeiculo = idTipoVeiculo;
       this.finalidade = finalidade;
       this.txtTipo = txtTipo;
    }
   
    public int getIdTipoVeiculo() {
        return this.idTipoVeiculo;
    }
    
    public void setIdTipoVeiculo(int idTipoVeiculo) {
        this.idTipoVeiculo = idTipoVeiculo;
    }
    public String getFinalidade() {
        return this.finalidade;
    }
    
    public void setFinalidade(String finalidade) {
        this.finalidade = finalidade;
    }
    public String getTxtTipo() {
        return this.txtTipo;
    }
    
    public void setTxtTipo(String txtTipo) {
        this.txtTipo = txtTipo;
    }




}


