package Modelo;
// Generated 24/01/2017 15:55:32 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TbUsuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int idUsuario;
    private String nome;
    private String sobrenome;
    private int idFuncao;
    private String telefone;
    private String email;
    private String usuario;
    private String senha;
    private Date dataNascimento;
    private Date dataAdmisssao;
    private Date dataDemissao;
    private String setor;
    private String observacao;

    public Usuario() {
    }

    public Usuario(int idUsuario, String nome, String sobrenome, int idFuncao, String usuario, String senha, Date dataAdmisssao) {
        this.idUsuario = idUsuario;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.idFuncao = idFuncao;
        this.usuario = usuario;
        this.senha = senha;
        this.dataAdmisssao = dataAdmisssao;
    }

    public Usuario(int idUsuario, String nome, String sobrenome, int idFuncao, String telefone, String email, String usuario, String senha, Date dataNascimento, Date dataAdmisssao, Date dataDemissao, String setor, String observacao) {
        this.idUsuario = idUsuario;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.idFuncao = idFuncao;
        this.telefone = telefone;
        this.email = email;
        this.usuario = usuario;
        this.senha = senha;
        this.dataNascimento = dataNascimento;
        this.dataAdmisssao = dataAdmisssao;
        this.dataDemissao = dataDemissao;
        this.setor = setor;
        this.observacao = observacao;
    }

    public Usuario(String nome, String sobrenome, int idFuncao, String telefone, String email, String usuario, String senha, Date dataNascimento, Date dataAdmisssao, String setor, String observacao) {
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.idFuncao = idFuncao;
        this.telefone = telefone;
        this.email = email;
        this.usuario = usuario;
        this.senha = senha;
        this.dataNascimento = dataNascimento;
        this.dataAdmisssao = dataAdmisssao;
        this.setor = setor;
        this.observacao = observacao;
    }

    public int getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSobrenome() {
        return this.sobrenome;
    }

    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    public int getIdFuncao() {
        return this.idFuncao;
    }

    public void setIdFuncao(int idFuncao) {
        this.idFuncao = idFuncao;
    }

    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public Date getDataNascimento() {
        return this.dataNascimento;
    }

    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    public Date getDataAdmisssao() {
        return this.dataAdmisssao;
    }

    public void setDataAdmisssao(Date dataAdmisssao) {
        this.dataAdmisssao = dataAdmisssao;
    }

    public Date getDataDemissao() {
        return this.dataDemissao;
    }

    public void setDataDemissao(Date dataDemissao) {
        this.dataDemissao = dataDemissao;
    }

    public String getSetor() {
        return this.setor;
    }

    public void setSetor(String setor) {
        this.setor = setor;
    }

    public String getObservacao() {
        return this.observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

}
